apache:
  build: images/apache-php/
  ports:
    - "50080:80"
    - "50022:22"
  volumes:
      - ./src:/var/www
  links:
    - mysql
  environment:
    VIRTUAL_HOST: app.proxy
mysql:
  image: mysql
  ports:
    - "53306:3306"
  volumes:
    - ./var/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_ROOT_HOST: '%'
proxy:
  image: jwilder/nginx-proxy
  ports:
    - 8080:80
  links:
    - apache
    - helloworld
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
helloworld:
  image: tutum/hello-world
  environment:
      VIRTUAL_HOST: hello.proxy


